# --------------------------------- #
#    Kanae's Configuration file     #
# --------------------------------- #
# This holds the configuration for Kanae. This file is not settable during runtime.
# If you wish to change the values, change and save, and restart your server

# Entries pertaining to Kanae are located here
kanae:

  # Host that the server will use.
  # Set to 0.0.0.0 if running in Docker
  host: "localhost"

  # Port that the server binds to.
  # Defaults to 8000
  port: 8000

  # Whether the development mode should be enabled or not
  # This should be disabled during production
  dev_mode: False

  # Prometheus exporter for Kanae. The following keys are used in order to control
  # the behavior of the Prometheus exporter
  prometheus:

    # Whether the Prometheus exporter is enabled or not
    enabled: False

    # The host that the Prometheus exporter will bind to. By default,
    # it will always be set to 127.0.0.1
    host: "localhost"

    # The port used for the Prometheus exporter. By default,
    # it will always be set to 9555
    port: 9555

  # Settings for Kanae's custom rate limiters
  limiter:

    # Whether the rate limiters are enabled or not
    enabled: True

    # Whether to inject the following headers into HTTP headers:
    # - X-RateLimit-Reset
    # - X-RateLimit-Remaining
    # - X-RateLimit-Limit
    # - Retry-After
    headers_enabled: False

    # Whether to check the rate limit before the request_before chain
    auto_check: True

    # Whether to swallow exceptions during rate limiting
    swallow_errors: True

    # The type of retry-after header to use. Must be http-date or delta-seconds
    # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Retry-After
    retry_after: "http-date"

    # Default ratelimits throughout all routes
    # See https://limits.readthedocs.io/en/stable/quickstart.html#rate-limit-string-notation
    default_limits:
      - "10/second"

    # Default shared ratelimits used throughout the application
    # This means that these limits below will be used as one rate limit throughout the application
    # LEAVE THIS BLANK if you have set the default limits
    application_limits: []
    
    ## Settings for falling back to memory-based storage
    in_memory_fallback:

      # Whether to enable this feature or not
      enabled: True

      # Limits used in the case of falling back to memory-based storage
      limits:
        - "15/second"

    # Prefix for each key
    key_prefix: ""

    # The style of the key. Must be either url or endpoint
    # - URL uses the actual path of the endpoint
    # - Endpoint uses the function module and name
    key_style: "url"

    # Valkey storage-backend URI
    storage_uri: "valkey://localhost:6379/"

# These are used by SuperTokens for our backend auth
auth:

  # Name of the app. Defaults to ucmacm-website
  name: "ucmacm-website"

  # Domain (includes https://) of the backend server (aka the domain for Kanae)
  # If you are testing, leave this to be http://localhost:8000 
  # MUST be replaced in production
  api_domain: "http://localhost:8000"

  # Domain (include https://) of the frontend website
  # If you are testing, leave this to be http://localhost:5173 and have the frontend up
  # MUST be replaced in production
  website_domain: "http://localhost:5173"

  # Allowed origins for CORS
  # Leave this as is unless for production
  allowed_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"

  # The backend SuperToken managed or core instance.
  # https://try.supertokens.com can be used for demo purposes, but we will be replacing it with a developer version
  connection_uri: 
    - ""

  # API key used for SuperTokens
  # Used on the hosted version
  api_key: ""


  # Social login providers (e.g. Google, Github, etc)
  providers:
    
    # OAuth2 login using Google accounts
    # Follow the setup instructions here: https://support.google.com/cloud/answer/6158849?hl=en
    # Auth callback is http://localhost:5173/auth/callback/google
    google:

      # OAuth2 client id
      client_id: ""

      # OAuth2 client secret
      client_secret: ""

      # OAuth2 scopes
      # Currently these are the ones needed:
      # - https://www.googleapis.com/auth/userinfo.profile
      # - https://www.googleapis.com/auth/userinfo.email
      scopes:
        - "https://www.googleapis.com/auth/userinfo.profile"
        - "https://www.googleapis.com/auth/userinfo.email"
  
# The PostgreSQL connection URI that is used to connect to the database
# The URI must be valid, and components will need to be quoted.
# See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
postgres_uri: "postgresql://user:password@localhost:5432/user"