version: '3'

tasks:
  dev-up:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml up -d

  dev-stop:
    preconditions:
      - test -f docker/docker-compose.dev.yml
    cmds:
      - docker compose -f docker/docker-compose.dev.yml stop

  start:
    cmds:
      - uvicorn launcher:app --app-dir=server --reload
    silent: true
  
  check:
    cmds:
      - ruff check server --fix --exit-non-zero-on-fix --config pyproject.toml
    silent: true

  fmt:
    cmds:
      - ruff format server --config pyproject.toml
    silent: true