name: kanae_dev

# For development purposes, it is recommended just to launch the server and use it's HMR feature instead
services:
  database:
    container_name: kanae_postgres
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    volumes:
      - database:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432

  valkey:
    container_name: kanae_valkey
    image: valkey/valkey:9-alpine
    healthcheck:
      test: valkey-cli PING || exit 1
    ports:
      - 6379:6379

volumes:
  database:
