name: kanae_dev

# For development purposes, it is recommended just to launch the server and use it's HMR feature instead
services:
  database:
    container_name: kanae_postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  valkey:
    container_name: kanae_valkey
    image: valkey/valkey:8-alpine
    healthcheck:
      test: valkey-cli PING || exit 1
    ports:
      - 6379:6379

volumes:
  database:
