{{- if .Values.renderSecrets }}
{{- $secrets := .Values.secrets }}
{{- range $key := keys $secrets }}
{{- $_ := required (printf "secrets.%s is required" $key) (get $secrets $key) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: kanae-env
  namespace: {{ .Values.namespace }}
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
type: Opaque
stringData:
  DB_PASSWORD: {{ $secrets.dbPassword | quote }}
  KRATOS_SECRETS_COOKIE: {{ $secrets.kratosSecretsCookie | quote }}
  KRATOS_SECRETS_CIPHER: {{ $secrets.kratosSecretsCipher | quote }}
  KRATOS_WEBHOOK_MASTER_KEY: {{ $secrets.kratosWebhookMasterKey | quote }}
  KRATOS_WEBHOOK_TOKEN_REGISTRATION: {{ $secrets.kratosWebhookTokenRegistration | quote }}
  KRATOS_WEBHOOK_TOKEN_SETTINGS: {{ $secrets.kratosWebhookTokenSettings | quote }}
  KRATOS_SMTP_URI: {{ $secrets.kratosSmtpUri | quote }}
  STORAGE_KEY_ID: {{ $secrets.storageKeyId | quote }}
  STORAGE_SECRET_KEY: {{ $secrets.storageSecretKey | quote }}
---
{{- $config := include "kanae.file" (list . "config.dist.yml") | fromYaml }}
{{- $_ := set $config.ory "kratos_webhook_master_key" $secrets.kratosWebhookMasterKey }}
{{- $_ := set $config.storage "key_id" $secrets.storageKeyId }}
{{- $_ := set $config.storage "secret_key" $secrets.storageSecretKey }}
{{- $_ := set $config "postgres_uri" (include "kanae.postgresUri" .) }}

apiVersion: v1
kind: Secret
metadata:
  name: kanae-config
  namespace: {{ .Values.namespace }}
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
type: Opaque
stringData:
  config.yml: |
    {{- $config | toYaml | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kanae-borg
  namespace: {{ .Values.namespace }}
  annotations:
    kapp.k14s.io/delete-strategy: "orphan"
type: Opaque
stringData:
  BORG_PASSPHRASE: {{ $secrets.borgPassphrase | quote }}
  AWS_ACCESS_KEY_ID: {{ $secrets.borgS3AccessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ $secrets.borgS3SecretKey | quote }}
{{- end }}
