#!/usr/bin/env bash
#
# Generates the values templates/secrets.yml renders into the kanae-env,
# kanae-config and kanae-borg Secrets, and writes them encrypted to
# deploy/kubernetes/secrets.sops.yml.
#
# This is safe to re-run. When executed again, only the missing ones
# are generated or prompted. DO NOT attempt to modify kratosSecretsCipher
# in any way. If you do, you basically make every single account useless.
#

set -euo pipefail

declare -A HOOKS=(
	[KRATOS_WEBHOOK_TOKEN_REGISTRATION]=kratosWebhookTokenRegistration
	[KRATOS_WEBHOOK_TOKEN_SETTINGS]=kratosWebhookTokenSettings
)

SCRIPT_PATH=$(readlink -f -- "${BASH_SOURCE[0]}")
KUBERNETES_DIR=${SCRIPT_PATH%/*}
ROOT_DIR=${KUBERNETES_DIR%/deploy/kubernetes}

ENCRYPTED=${ENCRYPTED:-$KUBERNETES_DIR/secrets.sops.yml}
DERIVE_SCRIPT=${DERIVE_SCRIPT:-$ROOT_DIR/scripts/derive-webhook-tokens.py}

if [[ -t 1 && -z ${NO_COLOR:-} ]]; then
	BLUE=$'\033[1;34m' RED=$'\033[1;31m' RESET=$'\033[0m'
else
	BLUE='' RED='' RESET=''
fi

log() { printf '%s==>%s %s\n' "$BLUE" "$RESET" "$*"; }
abort() {
	printf '%serror:%s %s\n' "$RED" "$RESET" "$*" >&2
	exit 1
}

LOCAL=
while getopts ':lh' opt; do
	case $opt in
		l) LOCAL=1 ;;
		h)
			printf 'usage: %s [-l] [-h]\n\n' "${0##*/}"
			printf '  -l  take the default for every asked value instead of prompting, for k3d\n'
			printf '  -h  show this help\n'
			exit 0
			;;
		*) abort "unknown option: -$OPTARG" ;;
	esac
done

for cmd in gum openssl sops uv yq; do
	command -v "$cmd" >/dev/null || abort "$cmd is required"
done

declare -A EXISTING=()
if [[ -f $ENCRYPTED ]]; then
	log "reading the values already in $ENCRYPTED"
	while IFS= read -r -d '' key && IFS= read -r -d '' value; do
		EXISTING[$key]=$value
	done < <(sops --decrypt "$ENCRYPTED" | yq -0 '.secrets | to_entries | map([.key, .value]) | flatten | .[]')
fi

KEYS=()
declare -A SECRETS=()
put() {
	local key=$1 value=$2
	[[ -n $value ]] || abort "$key cannot be empty"
	KEYS+=("$key")
	SECRETS[$key]=$value
}

generate() {
	local key=$1 bytes=$2
	put "$key" "${EXISTING[$key]:-$(openssl rand -hex "$bytes")}"
}

ask() {
	local key=$1 prompt=$2 default=${3:-} placeholder=${4:-}
	local value=${EXISTING[$key]:-${LOCAL:+$default}}
	[[ -n $value ]] || value=$(gum input --password --no-show-help \
		--prompt "$prompt: " --placeholder "$placeholder" --placeholder.foreground 245 </dev/tty)
	put "$key" "$value"
}

generate dbPassword 32
generate kratosSecretsCookie 32
generate kratosSecretsCipher 16
generate kratosWebhookMasterKey 32

log "deriving the Kratos webhook tokens from the master key"
tokens=$(cd "$ROOT_DIR" && uv run --with python-dotenv python "$DERIVE_SCRIPT" --stdin <<<"${SECRETS[kratosWebhookMasterKey]}")
while IFS='=' read -r name token; do
	put "${HOOKS[$name]}" "$token"
done <<<"$tokens"

ask kratosSmtpUri 'SMTP URI' smtp://mail:1025 'smtps://user:pass@host:465'

ask storageKeyId 'S3 Access Key ID' "GK$(openssl rand -hex 12)"
ask storageSecretKey 'S3 Secret Key ID' "$(openssl rand -hex 32)"

generate borgPassphrase 32
ask borgS3AccessKey 'Borg Repository S3 Access Key ID' local-borg-key-id
ask borgS3SecretKey 'Borg Repository S3 Secret Key' local-borg-secret-key

umask 077
TMP=$(mktemp "$ENCRYPTED.XXXXXX")
trap 'rm -f "$TMP"' EXIT

log "encrypting to $ENCRYPTED"
for key in "${KEYS[@]}"; do
	KEY=$key VALUE=${SECRETS[$key]} yq -n '{strenv(KEY): strenv(VALUE)}'
done \
	| yq '{"secrets": .} | . head_comment = "Generated by deploy/kubernetes/init.sh, which keeps every value already here."' \
	| sops --encrypt --filename-override "$ENCRYPTED" --input-type yaml /dev/stdin >"$TMP"

mv "$TMP" "$ENCRYPTED"
log "wrote $ENCRYPTED"
