secrets:
  dbPassword: REPLACE
  kratosSecretsCookie: REPLACE
  kratosSecretsCipher: REPLACE
  kratosWebhookMasterKey: REPLACE

  kratosWebhookTokenRegistration: REPLACE
  kratosWebhookTokenSettings: REPLACE

  kratosSmtpUri: REPLACE
  storageKeyId: REPLACE
  storageSecretKey: REPLACE

  borgPassphrase: REPLACE
  borgS3AccessKey: REPLACE
  borgS3SecretKey: REPLACE
