secrets:
  dbPassword: REPLACE
  kanaePassword: REPLACE
  kratosPassword: REPLACE
  ketoPassword: REPLACE
  postgresMonitorPassword: REPLACE
  kanaeMigratePassword: REPLACE
  kratosMigratePassword: REPLACE
  ketoMigratePassword: REPLACE
  kratosSecretsCookie: REPLACE
  kratosSecretsCipher: REPLACE
  kratosWebhookMasterKey: REPLACE

  kratosWebhookTokenRegistration: REPLACE
  kratosWebhookTokenSettings: REPLACE

  kratosSmtpUri: REPLACE
  storageKeyId: REPLACE
  storageSecretKey: REPLACE

  borgPassphrase: REPLACE
  borgS3AccessKey: REPLACE
  borgS3SecretKey: REPLACE
