#ENC[AES256_GCM,data:CrxRvvJA5OiAABIgDOg6nwCvCadogDuIJp+dKZ8x3kd+FUuCTI94V++WbVLrQPSUEeODv5h8VJoFnXRyoZPnF9CfNnSc1N9jrhDxUptV,iv:hibqzxHP3yCGngZG2rGKTM3wkyR19PZxWRaAJDNJIww=,tag:mXn5KnJ04o5Ywq4WXUz4AA==,type:comment]
secrets:
    dbPassword: ENC[AES256_GCM,data:xoQv+eEf1vqHIBAuNnwhl8jxEODmk5TL9KfQGERdRIA2D8ZtD+cpBYFPQQ9VtPu2m5UlTUx03+qzDWeFGC7wuA==,iv:WeQxgvz7fUSBp80GNPMottH/9Z3444ssrycGwcvXY4o=,tag:jf2qxwxR8VMeaVxHgCyYPA==,type:str]
    kratosSecretsCookie: ENC[AES256_GCM,data:Nlwuuqgb8iNNslQaVqjsrnkPHAfl0zPtVYC2ixnCDFq8a7G4URITx+aRfvZjeivrDGs2qBybdfIdMKkhXoSdxg==,iv:BWk560ep1AOTp9DJTISo36KHxEgALsMJ/tpEHu2x6GU=,tag:uBJ6d7fNfFlvQqqWuwuylw==,type:str]
    kratosSecretsCipher: ENC[AES256_GCM,data:DTGcg+R6bY49k5P+bweiEorOgJhzxZC/HJ6fttA4iWM=,iv:iSDIfspow/jSNVcTrczdQeamEwwUsI2U0c4sH2zoaKc=,tag:Q4pOFnZk7dSkTS9teRDuSw==,type:str]
    kratosWebhookMasterKey: ENC[AES256_GCM,data:3lgPdYb026dYNvVwWhXnvYK4XLzfAbeRYbmL+3KAyh/71BoZXdfG+o93JyYT+o/cXbGaBkXdGDDRRIaAdOPTgA==,iv:FigIWCkjmcEz0/TljxoXtddRPvM8TBlHHbv7zb0hMrc=,tag:dofwx2SY3MrHZxxEDSPxAg==,type:str]
    kratosWebhookTokenRegistration: ENC[AES256_GCM,data:iUKwC7ANwKCJSvQdh8HjfSublQFkQ65gbb0CYIJQg08l97BAnmdqXdqzV3f8c9zuQseOU7yg59CwZ2MqZFDJew==,iv:gnf7jUD0g4mXwCBMj2+mAE23JPO7eX7JCE8HF7VzhEg=,tag:kTOZjRxDtyb/Cn267X19oA==,type:str]
    kratosWebhookTokenSettings: ENC[AES256_GCM,data:ZbbZC8IEYsNKotla8KTxZsv8DgC5byTnLSJW0V2fYMrjC6ZoGQf5tw5lDVJjvyvZHxkY8+Opdn6ufGfCZOi+Yw==,iv:20rEOwnQQJECr2cZS3QodP+7fRtyQiBKCQn8XmL7jAM=,tag:10LvHMRqW+8k9JSSuHUFEg==,type:str]
    kratosSmtpUri: ENC[AES256_GCM,data:NlwyWrvApBjiNMNf1co/maw/lhH0fIR2wH9BJdzB+BSGGYg5FRTb+6qv,iv:z1BpPdYJJoEmTmmkh+U/suZ1CQd/pkrUztyN3qPNGRw=,tag:MjXvml0eTJQIUOkAH8exFg==,type:str]
    storageKeyId: ENC[AES256_GCM,data:5DPDtoM3kvMNsiGQN0FwUZB0Zdn3bAKs+9fcP+d1OFo22g==,iv:43PdAda7ZiBiAbaOsmBJCTiWcXr6WnWPCsS14XKRDo0=,tag:SwwnUkW1Z83apgn3CTHaPA==,type:str]
    storageSecretKey: ENC[AES256_GCM,data:6sQ+7LI/9g06J8Zbj5By8izQPNY7YuYOCIQFoEUwPvE8v/rI/3v4JEpEf9qxQvEAXdfL32mneUO4g0HLvrIZWg==,iv:7cArmA4pzQbC/p02OWJ0gbAo7WZ+YcdgBrjM1uK4dUY=,tag:WkpY/Y1oBGPFGl9lTps3PQ==,type:str]
    borgPassphrase: ENC[AES256_GCM,data:kRLHcuxzbAD59X3NfVCLcOe0Qpm2FhlGlGqVpbOU8Lv0WoGrqsD4K7q2BvHXf7TDwgWMDDc4Ty2HKgwjcvszdQ==,iv:iVhcxhSzBxzAzsIpWxy8p5oCXTXSEQpDa4WySckqyg4=,tag:kB2+yyeNYIypGhZeEVJ0Jw==,type:str]
    borgS3AccessKey: ENC[AES256_GCM,data:KPcPpisZr9vBkIfskRDTH/w=,iv:9YWKRKaJX/NxA7hVHLDKeefvVyS5S7ErN/+DMj8+APw=,tag:Qi/NiaM3FRKTk2UHvi7Yvw==,type:str]
    borgS3SecretKey: ENC[AES256_GCM,data:AKtCdmZkgut7ocel4aT5bAy/4ovUKw==,iv:2E1sfrrLkDhD4jXq6bBcE2C75xw3GRvykbGmJHY1OrM=,tag:G2hsnUc5Ijw2sA16Fq620Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQnI3UjVyYytIL2t1ODNP
            VklZTnRDc3Q4a3c4OTBjMTN0TmluSldtUlRBClZLMU1Gc2JCUityL3VuU2FjS0U0
            YmsxUEJMZFVxVmlDOU9tOUhFMTJhNFkKLS0tIGMrd2VsUmdaNnpBR2lNbTlLeVFx
            T2EyV2p4UExLcUdya3Bxb0RKWmp0dFkKcpjfGYtGAD82znnM/nGw+AAqdqroc1YZ
            v3bEyVwvtZQQfJ+kAkV73CNGzsbYmnilwVJhobRrqV/86GCOHKsp7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gfw0l0jf8m4j2fmpwldqm6ckxvvlwmvy8t3563yh3xc8rscp4ssszmykyf
    lastmodified: "2026-09-05T10:53:28Z"
    mac: ENC[AES256_GCM,data:+Wo7D5dLTF83uiDKlfspxgvnpQ/MpI45zVzwtKDZSMDUAKKZsuuNdfc53kc0tZFUGpCgk9AwrQV3U6WeE+5O5QF+Twu/9xXJsAbtQWIxWoPd3j62U3x2jVVxe1POEY7p3056KXDfs4fqV2DC8T6dfeqWY5Jk4XZLklre9pq00eU=,iv:OLQb0p1TBBgr8bfl/J7fz+rQNbceyIktDahI1rOaraE=,tag:pm2ZALsrcy0Mp12hpuTSKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
