image:
  tag: "edge@sha256:650a988f0157618daae81ebb3b8db815f48b164db89098e3e05b1ce76c46ef67"
  pullPolicy: IfNotPresent

kanae:
  allowedOrigins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
  limiter:
    enabled: false

postgres:
  storageClass: local-path
  storage: 2Gi

ory:
  secureCookies: false
