image:
  tag: "edge@sha256:4e1f69048f8a36ddd2cd1ea71d63241345877919e02d5a1118c1ca5afa57ae77"
  pullPolicy: Always

kanae:
  allowedOrigins:
    - "https://kanae:5173"
  limiter:
    enabled: false

gateway:
  hostname: kanae
  authRateLimit:
    requestsPerSecond: 50
  tls:
    provider: selfSigned

postgres:
  storageClass: local-path
  storage: 2Gi

ory:
  secureCookies: false
  publicOrigin: "https://kanae:5173"
