image:
  tag: "edge@sha256:10e6d9cfcaa39d54aae15bf674316bfc04fa57e70d66c312cf3d2a98dd981364"
  pullPolicy: IfNotPresent

kanae:
  allowedOrigins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
  limiter:
    enabled: false

postgres:
  storageClass: local-path
  storage: 2Gi

ory:
  secureCookies: false
