name: Lint
on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  Check:
    name: Check (${{ matrix.version }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        version: ['3.10', '3.11', '3.12', '3.13']

    env:
      UV_SYSTEM_PYTHON: 1

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6@d0cc045d04ccac9d8b7881df0226f9e82c39688e # 6.8.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -r requirements-dev.txt

      - name: Check typings
        run: |
          pyright server

      - name: Lint Codebase
        run: |
          ruff check server --exit-non-zero-on-fix

      - name: Check for formatting
        run: |
          ruff format server --check

