name: Test

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  Test:
    name: Test (${{ matrix.version }})
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        version: ['3.10', '3.11', '3.12', '3.13']

    env:
      TESTCONTAINER_DOCKER_NETWORK: kanae-testcontainers
      UV_SYSTEM_PYTHON: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # 6.8.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install -r requirements-dev.txt

      - name: Set up server configuration
        run: |
          cp config.dist.yml server/config.yml

      - name: Create Docker network for running Testcontainers
        run: sudo docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Run Tests
        run: |
          pytest
